<?php $view->title = "Billet Simple pour l'Alaska"; ?>
<?php ob_start(); ?>
<main>
	<?php if($view->user->post_can_create) { ?>
	<article class="fixer">
		<footer class="multibar">
			<?php if($view->user->post_can_create) { ?>
				<a class="right btn success" href="<?= url($view->urlPostCreate()); ?>">Créer</a>
			<?php } ?>
		</footer>
	</article>
	<?php } ?>
	<?php foreach ($posts as $post) { ?>
		<article class="fixer <?=$post['visibility']?:'warning';?>">
			<header><?= $post['title']; ?></header>
			<?= $post['content']; ?>
			<footer class="multibar">
				<span class="left">Publié le <?= $post['post_date']; ?></span>
				<?php if(!$post['visibility']) { ?>
					<a class="left btn warning">Non visible</a>
				<?php } ?>
				<?php if($post['post_can_delete']) { ?>
					<a class="right btn error" href="<?= url($view->urlPostDelete($post['id'])); ?>">Suprimer</a>
				<?php } ?>
				<?php if($post['post_can_publish']) { ?>
					<?php if(!$post['visibility']) { ?>
						<a class="right btn" href="<?= url($view->urlPostPublish($post['id'])); ?>">Publier</a>
					<?php } else {?>
						<a class="right btn" href="<?= url($view->urlPostUnpublish($post['id'])); ?>">Dépublier</a>
					<?php } ?>
				<?php } ?>
				<?php if($post['post_can_update']) { ?>
					<a class="right btn" href="<?= url($view->urlPostUpdate($post['id'])); ?>">Editer</a>
				<?php } ?>
				<a class="right btn" href="<?= url($view->urlPostRead($post['id'])); ?>">Lire plus...</a>
			</footer>
		</article>
	<?php } ?>
</main>
<?php return ob_get_clean(); ?>
