<?php $title = $post['title']." - Billet Simple pour l'Alaska"; ?>
<?php ob_start(); ?>
<main>
	<article class="fixer">
		<footer class="multibar">
			<a class="left btn" href="<?= url($view->urlPostList()); ?>">Retour</a>
		</footer>
	</article>
	<article id="post" class="fixer <?=$post['visibility']?:'warning';?>">
		<header class="multibar">
			<span class="left"><?= $post['title']; ?></span>
		</header>
		<div><?= $post['content']; ?></div>
		<footer class="multibar">
			<span class="left">Publié le <?= $post['post_date']; ?></span>
			<?php if(!$post['visibility']) { ?>
				<a class="left btn warning">Non visible</a>
			<?php } ?>
			<?php if($post['post_can_delete']) { ?>
				<a class="right btn error" href="<?= url($view->urlPostDelete($post['id'])); ?>">Suprimer</a>
			<?php } ?>
			<?php if($post['post_can_publish']) { ?>
				<?php if(!$post['visibility']) { ?>
					<a class="right btn" href="<?= url($view->urlPostPublish($post['id'])); ?>">Publier</a>
				<?php } else {?>
					<a class="right btn" href="<?= url($view->urlPostUnpublish($post['id'])); ?>">Dépublier</a>
				<?php } ?>
			<?php } ?>
			<?php if($post['post_can_update']) { ?>
				<a class="right btn" href="<?= url($view->urlPostUpdate($post['id'])); ?>">Editer</a>
			<?php } ?>
			<a class="right btn" href="<?= url($view->urlPostRead($post['id'])); ?>">Lire plus...</a>
		</footer>
	</article>
	<section class="fixer" id="comments">
		<h2>Commentaires</h2>
		<form action="<?= url($view->urlCommentCreate($post['id'])); ?>" method="post" class="grid">
			<label for="author">Auteur</label>
			<input type="text" disabled value="<?= $view->user->name; ?>" />
			<label for="comment">Commentaire</label>
			<textarea id="comment" name="comment"></textarea>
			<div class="line">
				<input type="submit" />
			</div>
		</form>
		<?php foreach ($post["comments"] as $comment) { ?>
			<article <?=$comment['visibility']?:'class="warning"';?>>
				<header class="multibar">
					<span class="left"><?= $comment['author']; ?> </span>
					<span class="right">le <?= $comment['post_date']; ?></span>
				</header>
				<div><?= $comment['content']; ?></div>
				<footer class="multibar">
					<?php if($comment['comment_can_delete']) { ?>
						<a class="right btn error" href="<?= url($view->urlCommentDelete($post['id'],$comment['id'])); ?>">suprimer</a>
					<?php } ?>
					<?php if(!$comment['visibility']) { ?>
						<a class="left btn warning">non visible</a>
						<?php if($comment['comment_can_publish']) { ?>
							<a class="right btn warning" href="<?= url($view->urlCommentPublish($post['id'],$comment['id'])); ?>">Publier</a>
						<?php } ?>
					<?php } elseif($comment['comment_can_unpublish']){ ?>
						<a class="right btn warning" href="<?= url($view->urlCommentUnpublish($post['id'],$comment['id'])); ?>">Dépublier</a>
					<?php } ?>
					<?php if($comment["reported"]) { ?>
						<a class="left btn error">signalé</a>
						<?php if($comment['comment_can_unreport']) { ?>
							<a class="right btn warning" href="<?= url($view->urlCommentUnreport($post['id'],$comment['id'])); ?>">désignaler</a>
						<?php } ?>
					<?php } elseif($comment['comment_can_report']){ ?>
						<a class="right btn warning" href="<?= url($view->urlCommentReport($post['id'],$comment['id'])); ?>">signaler</a>
					<?php } ?>
				</footer>
			</article>
		<?php } ?>
	</section>
</main>
<?php return ob_get_clean(); ?>
