<?php $view->title = "Billet Simple pour l'Alaska"; ?>
<?php ob_start(); ?>
<main>
	<?php foreach ($posts as $post) { ?>
		<article class="fixer">
			<header><?= $post['title']; ?></header>
			<?= $post['content']; ?>
			<footer class="multibar">
				<span class="left">Publié le <?= $post['post_date']; ?></span>
				<span class="right"><a class="btn" href="<?= url("/posts/".$post['id']);?>">Lire plus...</a></span>
			</footer>
		</article>
	<?php } ?>
</main>
<?php return ob_get_clean(); ?>
