<?php $title = 'Mon blog'; ?>
<?php ob_start(); ?>
<main class="fixer">
	<section>
		<article id="news">
			<h1><?= htmlspecialchars($post['title']); ?><em>le <?= $post['post_date_fr']; ?></em></h1>
			<p><?= nl2br(htmlspecialchars($post['content']));?></p>
			<section class="fixer" id="comments">
				<h2>Commentaires</h2>
				<form action="index.php?action=addComment&amp;id=<?= $post['id'] ?>" method="post">
					<div>
						<label for="author">Auteur</label><br />
						<input type="text" id="author" name="author" />
					</div>
					<div>
						<label for="comment">Commentaire</label><br />
						<textarea id="comment" name="comment"></textarea>
					</div>
					<div>
						<input type="submit" />
					</div>
				</form>
				<?php foreach ($comments as $comment) { ?>
				<article>
					<h3>
						<?= $comment['author']; /*?> auteur <?php*/ ?>
						<em>le <?= $comment['comment_date_fr']; /*?> 00/00/0000 à 00h00min00s <?php*/ ?></em>
						(<a href="?action=modComment&id=<?= $comment['id']; ?>">modifier</a>)
					</h3>
					<p><?= nl2br($comment['content']); /*?> content <?php*/ ?></p>
				</article>
				<?php } ?>
			</section>
		</article>
	</section>
</main>
<?php return ob_get_clean(); ?>
