<?php $view->title = "Billet Simple pour l'Alaska"; ?>
<?php ob_start(); ?>
<main>
	<?php if($view->user->post_can_create) { ?>
	<article class="fixer">
		<footer class="multibar">
			<?php if($view->user->post_can_create) { ?>
				<span class="right"><a class="btn warning" href="<?=url('/posts/create'); ?>">Créer</a></span>
			<?php } ?>
		</footer>
	</article>
	<?php } ?>
	<?php foreach ($posts as $post) { ?>
		<article class="fixer">
			<header><?= $post['title']; ?></header>
			<?= $post['content']; ?>
			<footer class="multibar">
				<span class="left">Publié le <?= $post['post_date']; ?></span>
				<?php if(!$post['visibility']) { ?>
					<span class="left"><a class="btn warning">Non visible</a></span>
				<?php } ?>
				<?php if($post['post_can_delete']) { ?>
					<span class="right"><a class="btn error" href="<?=url('/posts/'.$post['id'].'/delete'); ?>">Suprimer</a></span>
				<?php } ?>
				<?php if($post['post_can_publish']) { ?>
					<?php if(!$post['visibility']) { ?>
						<span class="right"><a class="btn" href="<?= url('/posts/'.$post['id']).'/publish';?>">Publier</a></span>
					<?php } else {?>
						<span class="right"><a class="btn" href="<?= url('/posts/'.$post['id']).'/unpublish';?>">Dépublier</a></span>
					<?php } ?>
				<?php } ?>
				<?php if($post['post_can_update']) { ?>
					<span class="right"><a class="btn" href="<?= url('/posts/'.$post['id'].'/update');?>">Editer</a></span>
				<?php } ?>
				<span class="right"><a class="btn" href="<?= url('/posts/'.$post['id']).'/read';?>">Lire plus...</a></span>
			</footer>
		</article>
	<?php } ?>
</main>
<?php return ob_get_clean(); ?>
