<?php $title = $post['title']." - Billet Simple pour l'Alaska"; ?>
<?php ob_start(); ?>
<main>
	<article id="post" class="fixer">
		<header class="multibar">
			<span class="left"><?= $post['id']; ?></span>
			<span><?= $post['title']; ?></span>
			<span class="right">Publié le <?= $post['post_date']; ?></span>
		</header>
		<div><?= $post['content']; ?></div>
	</article>
	<section class="fixer" id="comments">
		<h2>Commentaires</h2>
		<form action="index.php?action=addComment&amp;id=<?= $post['id'] ?>" method="post">
			<label for="author">Auteur</label>
			<input type="text" id="author" name="author" />
			<label for="comment">Commentaire</label>
			<textarea id="comment" name="comment"></textarea>
			<div class="line">
				<input type="submit" />
			</div>
		</form>
		<?php foreach ($post["comments"] as $comment) { ?>
		<article>
			<header class="multibar">
				<span class="left"><?= $comment['author']; ?> </span>
				<span>le <?= $comment['post_date']; ?></span>
				<span class="right"><a class="btn warning" href="?action=modComment&id=<?= $comment['id']; ?>">signaler</a></span>
			</header>
			<div><?= $comment['content']; ?></div>
		</article>
		<?php } ?>
	</section>
</main>
<?php return ob_get_clean(); ?>
