<?php ob_start(); ?>
<header>
	<div class="fixer multibar">
		<h1 class="left">
			<a href="<?= url($view->urlPostList()); ?>">
				<img src="<?= url('/res/logo.png');?>" height="48px" alt="Logo" />
				<p>Billet Simple pour l'alaska</p>
			</a>
		</h1>
		<nav class="right">
			<h2 class="hidden">Navigation</h2>
			<ul>
				<?php if($view->user->type == "Guest") { ?>
					<li><a href="<?= url($view->urlUserLogin()); ?>">Connexion</a> </li>
				<?php } else {?>
					<li><a href="<?= url($view->urlUserLogout()); ?>">Déconnexion</a> </li>
				<?php } ?>
			</ul>
		</nav>
	</div>
</header>
<?php return ob_get_clean(); ?>
