<?php ob_start(); ?>
<!DOCTYPE html>
<html lang="fr">

<head>

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<title><?= $view->title; ?></title>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
	<link href="<?= $view->uniqueurl('/res/style.css',true);?>" rel="stylesheet" />
	<?= $view->head; ?>

</head>

<body>

<?= $view->header; ?>
<?= $view->message; ?>
<?= $view->content; ?>
<?= $view->footer; ?>

</body>

</html>
<?php return ob_get_clean(); ?>
